name: URL Checker

on:  
  push:  
    paths:  
      - 'url.txt'  # 当txt文件发生变化时触发  
  workflow_dispatch:  # 手动触发  

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
            token: ${{ secrets.LIVELIST }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run URL checker
      run: python check_urls.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ok.txt
        git commit -m "Update ok.txt with valid URLs"
        git push