name: Copy Files to Live Directory  
  
on:  
  push:  
    paths:  
      - '**/*.txt'  
      - '**/*.m3u'  
  
jobs:  
  copy-files:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout source repository  
      uses: actions/checkout@v2  
  
    - name: Find files to copy  
      id: find-files  
      run: |  
        echo "::set-output name=files::$(find . -type f \( -iname '*.txt' -o -iname '*.m3u' \) -print0 | xargs -0 -n1 | sed 's/^\.\///')"  
  
    - name: Set up target repository  
      env:  
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}  
      run: |  
        export TARGET_REPO_URL="https://${{ secrets.TARGET_REPO_PAT }}@github.com/168xx/jdcj.git"  
        git clone "$TARGET_REPO_URL" target-repo  
        cd target-repo  
        mkdir -p live  
  
    - name: Copy files to target repository  
      env:  
        FILES: ${{ steps.find-files.outputs.files }}  
      run: |  
        IFS=$'\n' # 设置换行符为字段分隔符，以正确处理多行输出  
        for file in $FILES; do  
          cp "$PWD/$file" target-repo/live/  
        done  
  
    - name: Add, commit, and push changes  
      run: |  
        cd target-repo  
        git config --local user.email "github-actions@github.com"  
        git config --local user.name "github-actions"  
        git add live  
        if [ -n "$(git status --porcelain)" ]; then  
          git commit -m "Copied txt and m3u files from source repository"  
          git push origin main  
        else  
          echo "No changes to commit"  
        fi