name: 提取txt节目名单
  
on:  
  push:  
    paths:  
      - 'tv.txt'  # 当txt文件发生变化时触发  
  workflow_dispatch:  # 手动触发  
  
jobs:  
  remove-urls:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  
        with:
              token: ${{ secrets.LIVELIST }}
  
      - name: Set up environment  
        run: |  
          # 确保工作目录是干净的  
          git config --global user.name 'github-actions'  
          git config --global user.email 'github-actions@github.com'  
  
      - name: Remove URLs from tv.txt  
        run: |  
          # 使用 awk 处理文件，只保留逗号前的部分（频道名）  
          awk -F, '{if ($2 ~ /^http:\/\// || $2 ~ /^https:\/\//) $2=""; print $1","$2}' tv.txt | sed 's/,,/\n/g;s/,$//' > tt.txt 
     
      - name: Remove URLs more accurately  
        run: |  
          awk -F, '{  
            # 如果第二个字段是 URL，则只打印第一个字段（频道名）  
            if ($2 ~ /^http:\/\// || $2 ~ /^https:\/\//) {  
              print $1  
              # 如果需要在频道名后添加逗号（或其他分隔符），请取消下面一行的注释  
              # print $1","  
            }  
            # 如果第二个字段不是 URL，则打印整行  
            else {  
              print $0  
            }  
          }' tv.txt > tt_temp.txt && mv tt_temp.txt tt.txt  
  
      - name: Commit and push changes  
        run: |  
          # 检查是否有更改  
          if [ -n "$(git status --porcelain)" ]; then  
            # 添加更改  
            git add tt.txt  
            # 提交更改  
            git commit -m "Removed URLs from tv.txt and saved to tt.txt"  
            # 推送到仓库  
            git push  
          else  
            echo "No changes to commit"  
          fi