name: Copy Files to Another Repository  
  
on:  
  workflow_dispatch:  # 手动触发工作流  
  # 你也可以根据需要设置其他触发条件，例如 push 或 schedule  
  
jobs:  
  copy-files:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout source repository  
      uses: actions/checkout@v2  
  
    - name: Set up Git  
      run: |  
        git config --global user.name 'github-actions'  
        git config --global user.email 'github-actions@github.com'  
  
    - name: Install dependencies  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y rsync  
  
    - name: Fetch target repository  
      env:  
        TARGET_REPO_URL: ${{ secrets.TARGET_REPO_URL }}  # 格式为 git@github.com:user/repo.git  
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}  # 目标仓库的个人访问令牌  
      run: |  
        mkdir target-repo  
        cd target-repo  
        git init  
        git remote add origin "$TARGET_REPO_URL"  
        git fetch origin  
        git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages  # 假设目标分支是 gh-pages，根据实际情况修改  
  
    - name: Copy files to target repository  
      run: |  
        rsync -av --include='*/' --include='*.txt' --include='*.m3u' --exclude='*' . target-repo/live/  
  
    - name: Commit and push changes to target repository  
      env:  
        TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}  
      run: |  
        cd target-repo  
        git add live/  
        if [ -n "$(git status --porcelain)" ]; then  
          git commit -m "Update files from source repository"  
          git push -u origin gh-pages  
        else  
          echo "No changes to commit"  
        fi  
  
    # 可选：清理工作目录  
    - name: Cleanup  
      if: always()  
      run: |  
        rm -rf target-repo